### ISSUE TITLE
Suggestion: make more accessible for the non-tech-savvy user.

### ISSUE THREAD

**Issue by wdccdw** [readtedium/udm14#7]
I suspect there are many users who would find much of the text on the page incomprehensible.  I would like to send this to some of my more offline friends when they encounter Google frustration, but I suspect they will be bewildered by much of the text.  "&udm=14", "konami code".

Please consider no frills text, at least in the prominent positions.

**Comment by readtedium** [comment]
I apologize, I don’t think this is something I want to do with this project.

Please feel free to fork, I marked it CC0 for a reason, but my feeling is that watering down the sensibility or personality of things is not something I would like to do.
